# Generated by Django 5.0.4 on 2024-05-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='image_type',
            field=models.CharField(default='static', max_length=100),
        ),
    ]
