# Generated by Django 5.0.4 on 2024-05-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_advertise_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='test.png', upload_to='advertise_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='test.png', upload_to='advertise_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
