# Generated by Django 5.0.4 on 2024-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_category_image_service_image_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ImageField(upload_to='upload/advertise_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='test.png', upload_to='uploads/category_images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='test.png', upload_to='uploads/service_images/'),
        ),
    ]
