# Generated by Django 5.0.4 on 2024-05-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_advertise_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='name',
            field=models.CharField(default='main', max_length=100, null=True),
        ),
    ]
