# Generated by Django 5.0.4 on 2024-05-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_advertise_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='name',
            new_name='location',
        ),
    ]
