# Generated by Django 5.0.4 on 2024-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
